---

name: "Dive CI Analysis"
description: "Analyzes Docker images using Dive with CI configuration support and size validation"
inputs:
  image_name:
    description: "Docker image name"
    required: true
  ci_config:
    description: "Path to Dive CI configuration file (.dive-ci.yml)"
    required: true
  allow_large_image:
    description: "Set to true if the image size exceeds 1 GB"
    required: false
    default: "false"
  continue_on_fail:
    description: "Set false to fail launches that don't pass the test."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout action repository
      uses: actions/checkout@v4
      with:
          repository: dzhunli/image-analytics
    - run: |
        chmod +x src/main.sh
        src/main.sh "${{ inputs.image_name }}" "${{ inputs.ci_config }}" "${{ inputs.allow_large_image }}" "${{ inputs.continue_on_fail }}"
      shell: bash
