name: Lint-Check
on:
    push:
      paths:
        - '**/*.yml'
        - '**/*.yaml'
      paths-ignore:
        - 'compiled/**'
    pull_request:
      paths:
        - '**/*.yml'
        - '**/*.yaml'
      paths-ignore:
        - 'compiled/**'
    workflow_dispatch:
    workflow_call:

jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: './.yamllint'
          yamllint_file_or_dir: './action.yml'
          yamllint_strict: false
          yamllint_comment: false