name: PR-Pre-release Action

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  lint-check:
    uses: ./.github/workflows/lint-check.yaml

  trivy-check:
    name: trivy-check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  go-compile:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
          cache-dependency-path: src/go/go.sum

      - name: Install dependencies
        working-directory: src/go
        run: |
          go mod tidy

      - name: Build binaries
        working-directory: src/go
        run: |
          GOOS=linux GOARCH=amd64 go build -o godive-action
          mkdir -p ../../compiled
          mv godive-action ../../compiled/

  pre-release:
    needs: go-compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate tag from PR
        id: generate_tag
        run: |
          pr_number=${{ github.event.pull_request.number }}
          timestamp=$(date +%Y%m%d-%H%M%S)
          tag_name="pr-${pr_number}-${timestamp}"
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT

      - name: Generate release changelog
        uses: varrcan/generate-pretty-changelog-action@v1
        with:
          config: changelog.yaml
          use: github
          token: ${{ secrets.PAT_TOKEN }}

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag_name }}
          name: "Pre-release for PR #${{ github.event.pull_request.number }}"
          #body_path: CHANGELOG.md
          draft: false
          prerelease: true
          generate_release_notes: true
          files: compiled/godive-action
          token: ${{ secrets.PAT_TOKEN }}
      - name: Comment on PR with pre-release link
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
           const prNumber = context.payload.pull_request.number;
           const tag = "${{ steps.generate_tag.outputs.tag_name }}";
           const repo = context.repo.repo;
           const owner = context.repo.owner;
           const releaseUrl = `https://github.com/${owner}/${repo}/releases/tag/${tag}`;
            const body = `🔖 **Pre-release is ready:** [Download \`${tag}\`](${releaseUrl})`;
               await github.rest.issues.createComment({
                   issue_number: prNumber,
                   owner,
                   repo,
                   body
                 });