name: PR-Pre-release Action

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  lint-check:
    uses: ./.github/workflows/lint-check.yaml

  go-compile:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
          cache-dependency-path: src/go/go.sum

      - name: Install dependencies
        working-directory: src/go
        run: |
          go mod tidy

      - name: Build binaries
        working-directory: src/go
        run: |
          GOOS=linux GOARCH=amd64 go build -o godive-action
          mkdir -p ../../compiled
          mv godive-action ../../compiled/

  pre-release:
    needs: go-compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate tag from PR
        id: generate_tag
        run: |
          pr_number=${{ github.event.pull_request.number }}
          timestamp=$(date +%Y%m%d-%H%M%S)
          tag_name="pr-${pr_number}-${timestamp}"
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT

      - name: Generate release changelog
        uses: varrcan/generate-pretty-changelog-action@v1
        with:
          config: changelog.yaml
          use: github
          token: ${{ secrets.PAT_TOKEN }}

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag_name }}
          name: "Pre-release for PR #${{ github.event.pull_request.number }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: true
          generate_release_notes: true
          files: compiled/godive-action
          token: ${{ secrets.PAT_TOKEN }}
